# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb426f67601723f02f08a02357c7face1828172426e6967d6ca7bba3d5f607549cf77788b32e9ed841c377e0e72aa3483ccae300ccafd9c48942ba7226a4c20b

test:
  secret_key_base: c943480ea5e63e5df3c73f15a89dbf6b9f2a948e78224572dece38507ac5aab9d748d22e34f38a94065e45dc56ce7f621d49a286427ee0a970d3e214e7f6925d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
